# Generated by Django 3.2.13 on 2022-06-11 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220612_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackwrapper',
            name='playlist',
        ),
    ]
