# Generated by Django 3.2.13 on 2022-06-23 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_trackwrapper_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackwrapper',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='api.playlist'),
        ),
        migrations.AlterField(
            model_name='trackwrapper',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrappers', to='api.track'),
        ),
    ]
